stacks/spica/packages/common/src/input/components/string/string.component.html
stacks/spica/packages/common/src/input/input.module.ts
stacks/spica/src/function/pages/add/add.component.html
stacks/spica/src/function/pages/add/add.component.scss

This PR contains changes for
- Validation on function page in order to inform the user about validation errors.

feat(function): validation on add page

---

BUILD.bazel
WORKSPACE
deployment.yaml
tools/initcontainer/BUILD.bazel
tools/initcontainer/Dockerfile
tools/initcontainer/defs.bzl
tools/initcontainer/init.ts

This PR contains following changes;
- Init container image for mongodb. (so we can configure mongodb replset as we wish)
- Make spica stateful set, so we don't lose anything on updates.
- Make history work on test server

build: built initcontainer for mongodb

---

stacks/api/passport/identity/identity.controller.ts
stacks/api/passport/identity/identity.service.ts
stacks/api/passport/identity/index.ts
stacks/api/passport/identity/interface.ts
stacks/api/passport/jwt.strategy.ts
stacks/api/passport/passport.controller.ts
stacks/api/passport/passport.module.ts
stacks/api/passport/passport.service.ts
stacks/api/passport/policy/action.guard.ts
stacks/api/passport/policy/policy.controller.ts
stacks/api/passport/policy/policy.service.ts
stacks/spica/src/passport/pages/identity-add/identity-add.component.ts
stacks/spica/src/passport/pages/identity-index/identity-index.component.ts
stacks/spica/src/passport/pages/policy-add/policy-add.component.ts
stacks/spica/src/passport/pages/policy-index/policy-index.component.ts
stacks/spica/src/passport/services/policy.service.ts

This PR contains following changes;
- Seperation of identity and passport service 
- Pagination support for policy page and policy service.

feat(passport): support for pagination on policy page

---

stacks/BUILD.bazel
tools/bazel_stamp_vars.sh
tools/initcontainer/BUILD.bazel
tools/release/publish
tools/release/publish-latest
yarn.lock

This PR contains the following changes;
- New bazel targets for docker registry
- Release scripts for publish

chore: publish images to docker registry

---

stacks/spica/packages/common/src/input/components/array-schema/array-schema.component.html
stacks/spica/packages/common/src/input/components/array-schema/array-schema.component.scss
stacks/spica/packages/common/src/input/components/array-schema/array-schema.component.ts
stacks/spica/packages/common/src/input/components/array/array.component.html
stacks/spica/packages/common/src/input/components/array/array.component.ts
stacks/spica/packages/common/src/input/components/object-schema/object-schema.component.html
stacks/spica/packages/common/src/input/components/object-schema/object-schema.component.scss
stacks/spica/packages/common/src/input/components/object/object.component.html
stacks/spica/packages/common/src/input/input-schema-placer/input.schema.placer.ts
stacks/spica/packages/common/src/input/input.module.ts
stacks/spica/packages/common/src/input/validators.ts
stacks/spica/src/bucket/pages/bucket-add/bucket-add.component.html
stacks/spica/src/bucket/pages/bucket-add/bucket-add.component.scss

This PR contains the following changes;
- Support for minItems validator (array)
- Support for uniqueItems validator (array)
- Support for maxItems validator (array)
- Support for required validator (object)
- Reogranize of bucket add page styles

feat(common): support for minItems, uniqueItems, maxItems, required validators

---

stacks/api/function/engine/trigger/BUILD.bazel
stacks/api/function/engine/trigger/http.ts

fix(function): parse application/json and application/bson bodies

---

stacks/spica/src/bucket/bucket.module.ts
stacks/spica/src/bucket/pages/index/index.component.html
stacks/spica/src/bucket/pages/index/index.component.scss
stacks/spica/src/bucket/pages/index/index.component.ts

refactor(bucket): show load indicator and support for default sort

refactor(bucket): show load indicator and support for default sort

---

stacks/api/bucket/bucket-data.controller.ts

fix(bucket):  use facet if filter parameter is present

---

package.json
packages/core/testing/BUILD.bazel
packages/core/testing/index.ts
packages/core/testing/module.ts
packages/core/testing/websocket.ts
stacks/api/function/engine/BUILD.bazel
stacks/api/function/engine/engine.module.ts
stacks/api/function/engine/language/plugins/declarations.ts
stacks/api/function/engine/module/database.ts
stacks/api/function/engine/trigger/BUILD.bazel
stacks/api/function/engine/trigger/database.d.ts
stacks/api/function/engine/trigger/database.ts
stacks/api/function/engine/trigger/firehose.d.ts
stacks/api/function/engine/trigger/firehose.spec.ts
stacks/api/function/engine/trigger/firehose.ts
stacks/api/function/engine/trigger/http.d.ts
yarn.lock

feat(function): firehose trigger

---

stacks/api/function/engine/host.ts
stacks/api/function/function.controller.ts
stacks/spica/packages/core/layout/home/home.layout.html
stacks/spica/src/function/pages/add/add.component.html
stacks/spica/src/function/pages/add/add.component.ts
stacks/spica/src/passport/pages/identify/identify.component.html
stacks/spica/src/storage/components/picker/picker.component.html
stacks/spica/src/storage/components/picker/picker.component.scss
stacks/spica/src/storage/components/picker/picker.component.ts
stacks/spica/src/storage/components/picker/picker.directive.ts
stacks/spica/src/storage/components/storage-view/storage-view.component.html
stacks/spica/src/storage/components/storage-view/storage-view.component.ts
stacks/spica/src/storage/components/storage/storage.component.html

fix(storage): show wrong validation message

---

package.json
packages/core/schema/BUILD.bazel
packages/core/schema/validator.ts
packages/core/testing/BUILD.bazel
packages/core/testing/request.ts
stacks/api/function/engine/BUILD.bazel
stacks/api/function/engine/subscription/executor.ts
stacks/api/passport/policy/action.guard.ts
stacks/api/passport/testing/BUILD.bazel
stacks/api/passport/testing/module.spec.ts
stacks/api/passport/testing/module.ts
stacks/api/passport/testing/noop.strategy.ts
stacks/spica/src/storage/pages/image-editor/image-editor.component.ts
yarn.lock

Internal tracking: SP-66 Writing a mock passport module

test: provide testing utilies for passport

---

docs/content/guide/bucket.md
stacks/api/bucket/schemas/bucket.schema.json
stacks/spica/packages/common/input/components/boolean/boolean.component.html
stacks/spica/packages/common/input/input-schema-placer/input.schema.placer.html
stacks/spica/packages/common/input/validators.spec.ts
stacks/spica/src/bucket/pages/add/add.component.spec.ts
stacks/spica/src/bucket/pages/add/add.component.ts
stacks/spica/src/bucket/pages/bucket-add/bucket-add.component.html
stacks/spica/src/bucket/pages/bucket-add/bucket-add.component.spec.ts
stacks/spica/src/bucket/pages/index/index.component.scss

This pull request includes;
1. fix(bucket): add page is not opening after schema changed
2. fix(common): change boolean input title order
3. refactor(common): increase title maxLength
4. fix(bucket): set table width for more column

refactor: ui improvement and fix

---

packages/database/collection.ts
stacks/api/function/horizon/BUILD.bazel
stacks/api/function/horizon/src/horizon.ts
stacks/api/function/runtime/io/database.ts
stacks/api/function/runtime/node/entrypoint.ts
stacks/api/function/runtime/node/node.ts
stacks/api/function/runtime/src/runtime.ts
stacks/api/function/runtime/test/node/entrypoint.spec.ts
stacks/api/function/src/function.controller.ts
stacks/api/function/src/function.module.ts
stacks/api/function/src/log.service.ts
stacks/spica/src/function/pages/log-view/log-view.component.html
stacks/spica/src/function/pages/log-view/log-view.component.ts

https://dreamharvesters.atlassian.net/browse/SP-104

refactor(function): redirect function output to database

---

stacks/api/passport/apikey/apikey.controller.spec.ts
stacks/spica/src/passport/pages/apikey-add/apikey-add.component.html
stacks/spica/src/passport/pages/apikey-add/apikey-add.component.scss
stacks/spica/src/passport/pages/apikey-add/apikey-add.component.spec.ts
stacks/spica/src/passport/pages/apikey-index/apikey-index.component.html
stacks/spica/src/passport/pages/apikey-index/apikey-index.component.spec.ts
stacks/spica/src/passport/pages/apikey-index/apikey-index.component.ts
stacks/spica/src/passport/services/apikey.service.ts

https://dreamharvesters.atlassian.net/browse/SP-130
https://dreamharvesters.atlassian.net/browse/SP-131

feat(passport): complete api key enable/disable and delete actions

---

stacks/spica/src/passport/pages/policy-add/policy-add.component.spec.ts
stacks/spica/src/passport/pages/policy-add/policy-add.component.ts

https://dreamharvesters.atlassian.net/browse/SP-100

fix(passport): policy statement action selection

---

stacks/spica/src/bucket/pages/add/add.component.html
stacks/spica/src/bucket/pages/add/add.component.ts

https://dreamharvesters.atlassian.net/browse/SP-156

fix(bucket): add button is still clickable while inserting data

---

stacks/spica/packages/material/clipboard/clipboard.directive.spec.ts
stacks/spica/packages/material/clipboard/clipboard.directive.ts

https://dreamharvesters.atlassian.net/browse/SP-144

fix(bucket): copy bucket id to clipboard

---

.bazelrc
.circleci/config.yml
WORKSPACE
package.json
scripts/ibazel.js
stacks/api/BUILD.bazel
stacks/api/function/runtime/node/BUILD.bazel
stacks/cli/BUILD.bazel
tools/dgeni/BUILD.bazel
tools/dgeni/index.bzl
yarn.lock

FYI: Some of the changes are not related to the fix. I had to make those changes cause I had to upgrade javascript rules.

build: update bazel dependencies and fix runtime dependency issues

---

stacks/api/function/enqueuer/BUILD.bazel
stacks/api/function/enqueuer/src/index.ts
stacks/api/function/enqueuer/src/system.ts
stacks/api/function/enqueuer/test/BUILD.bazel
stacks/api/function/enqueuer/test/system.spec.ts
stacks/api/function/horizon/src/horizon.ts
stacks/api/function/queue/proto/event.proto
stacks/api/function/queue/proto/event.ts
stacks/api/function/runtime/node/entrypoint.ts
stacks/api/function/src/engine.ts
stacks/api/function/src/schema/system.json

Internally tracked as SP-122.
Also, could you please check out the branch see if the tests are passing on your end also.
Cmd: `yarn bazel test //stacks/api/function/...`

feat(function): introduce system enqueuer

---

stacks/spica/packages/common/input/components/object/object.component.scss
stacks/spica/src/bucket/components/location/location.component.html
stacks/spica/src/bucket/pages/welcome/welcome.component.html
stacks/spica/src/bucket/pages/welcome/welcome.component.scss

Tracked as  (#SP-175, #SP-180, #SP-188).

fix: some interface inconsistencies.

---

stacks/api/function/src/interface.ts
stacks/api/function/src/schema/enqueuer.resolver.ts
stacks/cli/src/interface.ts
stacks/spica/src/function/interface.ts
stacks/spica/src/function/pages/add/add.component.html

fix(function): do not enforce to have a handler as default

---

stacks/api/function/runtime/io/database.ts
stacks/api/function/runtime/test/io/database.spec.ts

Tracked as SP-187 as internally.

fix(function): do not create logs collection as capped

---

stacks/spica/src/function/function.service.ts
stacks/spica/src/function/pages/add/add.component.html
stacks/spica/src/function/pages/add/add.component.scss
stacks/spica/src/function/pages/add/add.component.ts

Tracked as SP-208 as Internally.

fix(function): show an indicator while saving the function

---

stacks/api/function/queue/src/event.ts

https://dreamharvesters.atlassian.net/browse/SP-301

fix(functions): functions doesn't use the pooled processes

---

packages/core/middlewares.ts

fix(core): allow cors allowed headers to be manipulated via access-control-request-headers

---

packages/core/websocket/src/adapter.ts
stacks/api/bucket/bucket-data.controller.ts
stacks/api/bucket/hooks/src/dispatcher.ts
stacks/api/bucket/hooks/src/module.ts
stacks/api/bucket/hooks/test/BUILD.bazel
stacks/api/bucket/hooks/test/src/integration.spec.ts
stacks/api/bucket/hooks/test/src/module.spec.ts
stacks/api/bucket/realtime/BUILD.bazel
stacks/api/bucket/realtime/src/realtime.gateway.ts
stacks/api/passport/policy/action.guard.ts

includes SP-334
also includes an unintentional fix for SP-337

feat(bucket): add stream hook for realtime

---

stacks/api/function/src/function.controller.ts
stacks/spica/src/function/pages/add/add.component.ts

fix(function): bucket triggered function does not save and error message stays on each function

---

scripts/function_link_devkit_packages.sh
stacks/api/function/packages/BUILD.bazel
stacks/api/function/packages/dashboard/BUILD.bazel
stacks/api/function/packages/dashboard/package.json
stacks/api/function/packages/dashboard/tsconfig.json
stacks/api/function/packages/database/BUILD.bazel
stacks/api/function/packages/database/index.ts
stacks/api/function/packages/database/package.json
stacks/api/function/packages/database/scripts/postinstall.js
stacks/api/function/packages/database/src/check.ts
stacks/api/function/packages/database/src/database.ts
stacks/api/function/packages/database/src/objectid.ts
stacks/api/function/packages/database/tsconfig.json
stacks/api/function/packages/rollup.config.js
stacks/api/function/packages/tsconfig.json
stacks/api/function/runtime/node/entrypoint.js
stacks/api/function/src/function.controller.ts
stacks/spica/src/function/pages/add/add.component.scss
stacks/spica/src/function/pages/add/add.component.ts

Support for syntaxes like `const {} = require(module)`
Support for syntaxes like `import {} from "module"` for Javascript Language

feat(function): esm support for devkit packages

---

charts/spica/templates/application.yaml
charts/spica/templates/database.yaml

fix(charts): mount database properly

---

stacks/api/bucket/hooks/test/integration.spec.ts
stacks/api/function/compiler/typescript/src/typescript.ts
stacks/api/function/runtime/node/node.ts
stacks/api/function/runtime/src/runtime.ts
stacks/api/function/scheduler/src/options.ts
stacks/api/function/scheduler/src/scheduler.ts
stacks/api/function/scheduler/test/injection.spec.ts
stacks/api/function/scheduler/test/scheduler.spec.ts
stacks/api/function/src/engine.ts
stacks/api/function/src/function.module.ts
stacks/api/function/test/engine.spec.ts
stacks/api/main.ts

feat(function): add an option to prevent worker burst

---

stacks/api/bucket/hooks/src/module.ts
stacks/api/bucket/hooks/test/module.spec.ts
stacks/api/bucket/src/bucket-data.controller.ts

fix(bucket): correct the typo in bucket trigger types

---

stacks/spica/src/storage/components/image-editor/image-editor.component.ts
stacks/spica/src/storage/storage.service.ts

Alternative solution is the create a new schema to validate update requests.

fix(storage): validation errors on object update

---

stacks/api/function/packages/bucket/src/bucket.ts
stacks/api/function/packages/bucket/src/interface.ts
stacks/api/function/packages/bucket/test/bucket.spec.ts
stacks/api/function/src/log/src/realtime.gateway.ts

Additional changes on @spica-devkit/bucket

fix(function): update realtime logs due to filter expression changes

---

stacks/spica/packages/core/layout/home/home.layout.spec.ts
stacks/spica/src/app.module.ts
stacks/spica/src/bucket/pages/add-field-modal/add-field-modal.component.html
stacks/spica/src/bucket/pages/add-field-modal/add-field-modal.component.spec.ts
stacks/spica/src/bucket/pages/add-field-modal/add-field-modal.component.ts
stacks/spica/src/bucket/pages/add/add.component.spec.ts
stacks/spica/src/bucket/pages/bucket-add/bucket-add.component.spec.ts
stacks/spica/src/bucket/pages/index/index.component.spec.ts
stacks/spica/src/function/pages/add/add.component.spec.ts
stacks/spica/src/function/pages/log-view/log-view.component.spec.ts
stacks/spica/src/function/pages/webhook-add/webhook-add.component.spec.ts
stacks/spica/src/function/pages/webhook-index/webhook-index.component.spec.ts
stacks/spica/src/passport/components/policy-resource-add/policy-resource-add.spec.ts
stacks/spica/src/passport/pages/apikey-add/apikey-add.component.spec.ts
stacks/spica/src/passport/pages/apikey-index/apikey-index.component.spec.ts
stacks/spica/src/passport/pages/identity-add/identity-add.component.spec.ts
stacks/spica/src/passport/pages/identity-index/identity-index.component.spec.ts
stacks/spica/src/passport/pages/policy-add/policy-add.component.spec.ts
stacks/spica/src/passport/pages/policy-index/policy-index.component.spec.ts
stacks/spica/src/passport/pages/strategies/strategies.component.spec.ts
stacks/spica/src/storage/pages/index/index.component.spec.ts

CanInteractTest class import target changes are unrelated changes on this PR.

refactor(common): validation error behavior

---

stacks/spica/container/nginx.conf

Reverts spica-engine/spica#734

Revert "chore: nginx configuration update"

---

stacks/api/bucket/src/machinery.ts

For more details, see https://dreamharvesters.atlassian.net/browse/SP-722

fix(machinery): allow user to send more complex relations

---

stacks/api/bucket/hooks/BUILD.bazel
stacks/api/bucket/hooks/src/module.ts
stacks/api/bucket/hooks/test/module.spec.ts
stacks/api/bucket/services/src/bucket.service.ts
stacks/api/function/services/src/options.ts
stacks/api/function/src/engine.ts
stacks/api/function/test/engine.spec.ts
stacks/api/function/webhook/BUILD.bazel
stacks/api/function/webhook/src/webhook.controller.ts
stacks/api/function/webhook/test/webhook.controller.spec.ts
stacks/spica/src/function/pages/add/add.component.spec.ts
stacks/spica/src/function/pages/add/add.component.ts
stacks/spica/src/function/pages/webhook-add/webhook-add.component.html
stacks/spica/src/passport/components/policy-resource-add/policy-resource-add.component.html
stacks/spica/src/passport/components/policy-resource-add/policy-resource-add.component.ts

This pull request includes some fixes of [SP-730](https://dreamharvesters.atlassian.net/browse/SP-730)

fix(passport): show selectable resources on statement edit modal

---

.buildkite/pipeline.yaml

Reverts spica-engine/spica#1002

Revert "build: update secrets path for new machine"

---

.buildkite/pipeline.yaml

Reverts spica-engine/spica#999

Revert "build: update volume paths for the new machine"

---

apps/api/src/function/test/e2e.spec.ts
apps/api/src/function/test/engine.spec.ts
apps/api/src/replication/src/reducer.ts

Disabled tests will be enabled at this [task](https://trello.com/c/x77UZqXN/195-spica-195-enable-schedule-queue-shifting-tests)

test: return appropriate response from mongodb delete action

---

apps/api/package.json
apps/api/src/function/packages/storage/test/storage.integration.spec.ts
apps/api/src/main.ts
apps/api/src/status/test/controller.spec.ts
apps/api/src/storage/src/storage.controller.ts
apps/api/src/storage/src/storage.module.ts
apps/api/src/storage/src/storage.service.ts
apps/api/src/storage/src/strategy/aws.s3.ts
apps/api/src/storage/src/strategy/base-strategy.ts
apps/api/src/storage/src/strategy/default.ts
apps/api/src/storage/src/strategy/gcloud.ts
apps/api/src/storage/src/strategy/strategy.ts
apps/api/src/storage/test/storage.acceptance.spec.ts
apps/api/src/storage/test/storage.module.spec.ts
apps/api/src/storage/test/storage.service.spec.ts
apps/api/src/storage/test/strategy/default.spec.ts
apps/api/src/storage/test/strategy/gcloud.spec.ts
libs/interface/storage/src/options.ts
yarn.lock

EXAMPLE CLIENTS
Nodejs:
```
import fs from "fs";
import tus from "tus-js-client";
const filename = "Docker.dmg";
const filePath = "./" + filename;
const fileSize = fs.statSync(filePath).size;
const fileStream = fs.createReadStream(filePath);
const upload = new tus.Upload(fileStream, {
endpoint: "http://localhost:4300/storage/resumable",
metadata: {
filename,
filetype: "application/x-apple-diskimage",
},
uploadSize: fileSize,
urlStorage: new tus.FileUrlStorage("./tus-urls.json"), // <= save URL
onError(error) {
console.error("❌ Upload failed:", error);
},
onProgress(bytesUploaded, bytesTotal) {
const percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
console.log(`📤 Uploaded ${percentage}%`);
},
onSuccess() {
console.log("✅ Upload finished:", upload.url);
},
}); …
```

feat(api): introduce resumable uploads for storage
